- deps.edn
- reflection.json
I checked out this project from https://github.com/taylorwood/clj.native-image/issues/5 and made a couple tweaks to get it building with GraalVM 19.0.0.
Running clj-kondo native image on itself:
```
➜  clj-kondo git:(native-image-fix) /usr/bin/time -l ./clj-kondo --lint .
./corpus/cljc/datascript.cljc:8:1: error: wrong number of args (2) passed to datascript.db/seqable?
8<------------------------------------------
./src/clj_kondo/main.clj:5:5: warning: unused namespace clj-kondo.impl.rewrite-clj-patch
linting took 560ms, errors: 39, warnings: 23
0.58 real         0.42 user         0.12 sys
258760704  maximum resident set size
0  average shared memory size
0  average unshared data size
0  average unshared stack size
63262  page reclaims
0  page faults
0  swaps
0  block input operations
0 …
```
> GraalVM native image tweaks

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/linters.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/main_test.clj
> lint keyword calls

- README.md
`clj` uses rlwrap, which will produce a warning in CI environments
as it's not a terminal where rlwrap can be used.  For this exact
use-case, `clojure` is more than fine, as rlwrap is not necessary for
the `-Spath` option.
> Advocate use of `clojure` over `clj`

- .github/ISSUE_TEMPLATE/bug_report.md
This makes it more likely that people will try and find the right version.
> Add information on how to get the version of clj-kondo in use

- src/clj_kondo/impl/analyzer.clj
Hey @borkdude, here's the tiny fix we talked about yesterday at heartofclojure. I wanted to add some sort of test for it but I don't know where would be the best place to do so. Maybe I just add this line to `corpus/unresolved_symbol.clj`:
```clj
(when-first [a [1 2 3]] a)
```
wdyt?
> Correctly analyze `clojure.core/when-first` macro

- src/clj_kondo/impl/linters.clj
- test/clj_kondo/main_test.clj
**version**
clj-kondo v2019.08.01-alpha-SNAPSHOT
**platform**
Linux, GraalVM
**problem**
Namespaces local config in the metadata was ignored when registering findings for `:unused-namespace` and `:unused-referred-var`.
**repro**
```bash
$> clj-kondo --lint - << EOF
(ns ^{:clj-kondo/config
'{:linters {:unused-namespace {:exclude [clojure.pprint]}
:unused-referred-var {:exclude {clojure.pprint [pprint]}}}}}
user
(:require [clojure.pprint :refer [pprint]]))
EOF
<stdin>:5:14: warning: namespace clojure.pprint is required but never used
<stdin>:5:37: warning: #'clojure.pprint/pprint is referred but never used
linting took 26ms, errors: 0, warnings: 2
```
**expected behavior**
No warnings
---
Not sure if the tests I added are the most convenient or if there's a different place where this could …
> Use namespace's local config when running `lint-unused-namespaces!`

- src/clj_kondo/impl/config.clj
@borkdude Not sure if this is interesting for you to add to the default configuration, but just in case :) feel free to close it if you prefer not to provide a default linter for `clojure.test.check.generators/let`
In the current implementation:
```bash
$> clj-kondo --lint - << EOF
(ns test
(:require [clojure.test.check.generators :as gen]))
(gen/let [x 1] x) 
EOF
<stdin>:3:11: info: unresolved symbol x
linting took 24ms, errors: 0, warnings: 0
```
This PR removes the false positive.
> Add default linter for `clojure.test.check.generators/let`

- corpus/cljs_ns_as_as_object.cljs
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/main_test.clj
In Cljs, check if a name referes to a namespace alias directly.
> Fix #446: Handle using required namespace as object in Cljs

- analysis/README.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/analysis_test.clj
This would be useful for:
- Auto-inserting the require based on existing aliases (e.g. str/ should
insert clojure.string)
- Ensuring a consistent use of aliases in a project.
> Add alias / :as to analysis data

- src/clj_kondo/impl/types/clojure/core.clj
`clj-kondo --lint - <<< '(partition 10 10 nil [1 2 3 4])'`
should now work correctly. Third parameter (pad) is a collection.
> Fix partition signature when 4 parameters provided

- doc/editor-integration.md
1. `show console` should be on `never`, otherwise the terminal pops up after every file change.
2. added a custom config usage example - should use `"`. using `' ` as the readme suggests makes clj-kondo stop working with intellij.
3. set `level` to `global` to enable the watcher for all future projects.
4. `scope` should be `current file` or `project files`.
> updated intellij integration instructions

- parser/clj_kondo/impl/rewrite_clj/parser/core.clj
- parser/clj_kondo/impl/rewrite_clj/parser/utils.clj
- parser/clj_kondo/impl/rewrite_clj/reader.clj
- test/clj_kondo/impl/parser_test.clj
rewrite-clj has two `throw-reader` functions, with slightly different
behaviour. One expectects a list of strings, the other expects a format
string and matching arguments.
Replace both functions with a single one.
Add a full regression test that has example source code that excercises
all call sites of throw-reader, to ensure that this refactor does not
change behaviour.
> Consolidate throw-reader functions

- parser/clj_kondo/impl/rewrite_clj/parser/core.clj
- parser/clj_kondo/impl/rewrite_clj/parser/utils.clj
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/impl/analyzer_test.clj
- test/clj_kondo/impl/parser_test.clj
- test/clj_kondo/main_test.clj
Fixes #514
The error messages from the vendored copy of rewrite-clj are not as
helpful as they could be. I often have a hard time finding the location
of a mismatched bracket, since the error message refers to the EOF at
the end of the file, and not the opening paren.
To fix this we allow rewrite-clj to throw exceptions containing a
sequence of errors.
Changes:
- Make rewrite-clj throw ex-info instead of Exception. The ex-data
contains a :findings key, which is a sequence of findings in the format
expected by clj-kondo
- Change rewrite-clj.parser.core/*delimiters* to keep track of a tuple
of [open, close, row, col] rather than just the expected closing
delimiter. The extra three fields allow is to construct more informative
error messages when a parse error occurs.
- If an EOF is …
> Better error messages for syntax errors

- inlined/clj_kondo/impl/toolsreader/v1v2v2/clojure/tools/reader/edn.clj
- inlined/clj_kondo/impl/toolsreader/v1v2v2/clojure/tools/reader/impl/errors.clj
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/impl/analyzer_test.clj
- test/clj_kondo/impl/parser_test.clj
By passing an indexing reader to the edn parser, line and column
information is produced in the error messages.
clj-kondo.impl.toolsreader.v1v2v2.clojure.tools.reader.impl.errors/throw-ex
Remove the string formatting here. All of the data required by
->findings is contained in the ex-data. If we don't remove this string
formatting, then the error message shown to the user will be prepended
with `[line x, col y] `.
clj-kondo.impl.analyzer/->findings
Now that tools.reader is throwing data, we need to update `->findings`
to be able to read that data correctly.
Add unit test to ensure that line data comes out of the parser, and an
integration to ensure that `->findings` works.
> Use an indexing reader when parsing EDN

- corpus/cljs_ns_as_as_object.cljs
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/macroexpand.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/main_test.clj
This fixes the issue #533 with CLJS when module export is a constructor that
is called in the short-hand constructor notation. It might also be
useful later for analyzing Java interop.
---
Rationale: just hacking special logic when cljs calls a function with a dot in the end didn't feel right, when Clojure always expands these calls to `new`.
However, this breaks tests at the moment. I'll fix them but just wanted to submit this code for comments.
> [#533] macroexpand (Obj.) to (new Obj)

- analysis/README.md
The analysis doc mentions :lang for :var-definitions and :var-usages, but not for :namespaces-definitions and :namespaces-usages.  This is an attempt to fill that info in a bit.
> Add additional :lang descriptions to analysis doc

- doc/editor-integration.md
Currently it's easy to miss that there's a difference in how you install this on `master` vs `develop` `spacemacs` branches.
Or mainly because I installed this on `master` first and then upgraded to `develop` and was wondering why it wasn't working 😅
> Make develop vs master spacemacs install more obvious

- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/main_test.clj
We should only complain about inconsistent ns aliases when the alias is actually present.
Fixes #650
> Only complain about inconsistent ns alias when an alias is defined

- src/clj_kondo/impl/types/clojure/core.clj
- test/clj_kondo/types_test.clj
As discussed in the Slack channel, this PR corrects the argument types for some clojure.core functions from `:associative` -> `:nilable/associative`.
Also adds spec for `get` and fixes wrong type signatures of `keys` and `vals`.
> Fix some type specs for clojure.core associative functions

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/types.clj
- src/clj_kondo/impl/types/clojure/core.clj
- test/clj_kondo/types_test.clj
As per the discussion in #657, and open to changes/rejection.
I tried to add a :stack = #{:list :vector} type as suggested, but was forced to expand its scope so much due to the transitive requirements that it ended up being nearly useless.
Given that, perhaps `peek` and `pop` should be simply specced as `#{:list :vector}` instead of introducing a new type?
> Changes to seq-returning functions

- doc/editor-integration.md
Following the current doc produces a lot of cache directories/files everywhere in the project, where/when the linter is executed. Also, this PR removes confusing `.` characters, we don't know if they should be part of the input or if they end the sentence. For consistency's sake it also removes all ending `.`. I only did it for Cursive as I noticed no other editor integration specified the `cache` option manually.
> Don't specify current directory as cache

- README.md
- doc/ci-integration.md
Add a new page named "CI integration" where we can collect all the useful info about connecting `clj-kondo` to the existing workflow of a project.
> Add CI integration doc page

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/types.clj
- src/clj_kondo/impl/types/clojure/core.clj
- test/clj_kondo/impl/types_test.clj
- test/clj_kondo/types_test.clj
This PR adds specs for most predicates ending in `?` that are simple any->boolean type-checking functions, excluding those like `extends?`, `future-done?` etc.), and common seq functions. Also removes a reference to `:seqable-out` I missed from the last PR.
`script/diff` shows no linting or performance difference from the current master branch.
> Add type specs for more clojure.core functions

- src/clj_kondo/impl/core.clj
fixes ClassCastException bc string is passed but `read-edn-file` has type hint for `java.io.File`
> fixes parsing config from file path from cli. issue #719

- corpus/config/invalid_arity.edn
- test/clj_kondo/core_test.clj
added a single simple test. without the config arg, there are 9 errors and 7 warnings, but with the config there are 0 for each. let me know if this works or if we should check some other cases
> adds a test which passes a config as a file path. relevant to issue #719

- doc/jvm.md
There were two missing `}` in the documentation. no additional changes
> fix doc/jvm.md missing }

- src/clj_kondo/impl/linters.clj
This is the only flaw Eastwood found in the codebase (other than a `clojure.core/type` shadowing in `defn reg-finding!` - not everyone likes those fixed, so I didn't out of caution)
> `impl.linters`: unwrap redundant `and`

- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/single_arity_comparison_test.clj
- test/clj_kondo/single_operand_comparison_test.clj
Request adds linting for calls of logical operators and comparators with single arity that always produce the same value.
Linting diff:
```bash
130d129
< cljs/analyzer.cljc:2869:10: warning: 1-arity use of cljs.core/or always evaluates to the same value
332,335d330
< cljs/core.cljs:1872:11: warning: 1-arity use of cljs.core/and always evaluates to the same value
< cljs/core.cljs:1877:11: warning: 1-arity use of cljs.core/and always evaluates to the same value
< cljs/core.cljs:1905:11: warning: 1-arity use of cljs.core/and always evaluates to the same value
< cljs/core.cljs:1910:11: warning: 1-arity use of cljs.core/and always evaluates to the same value
1922,1923c1917
< src/clj_kondo/impl/linters.clj:29:19: warning: 1-arity use of clojure.core/and always evaluates to the same value
< …
```
> [#260] Add linting for single arity comparison

- doc/editor-integration.md
Updates the install instructions for people without Cursive/Ultimate
Fixes #786
> [doc] Intellij setup: Cursive/Ultimate not required

- script/install-clj-kondo
Hey,
I have added a new parameter `--download-dir` to the install script as requested by [this issue](https://github.com/borkdude/clj-kondo/issues/748)
Hope this is ok and let me know if anything can be improved
> [#748] add download directory parameter to install script

- corpus/jdbc/cjj_test.clj
- corpus/jdbc/next.clj
- corpus/jdbc/next_test.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/common.clj
- src/clj_kondo/impl/analyzer/jdbc.clj
- test/clj_kondo/jdbc_test.clj
Adds a JDBC analyzer. Mostly treats the `with-*` macros like `let` but adds checks for 2 or 3 forms and that the first form is a symbol (limited binding forms are valid).
> Fixes #821 by adding analyzers for common JDBC wrappers

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/main_test.clj
In this PR we:
- Extract the code for "Missing else branch" linter into its own function. Now the `analyze-if` will not complain about arity 2, which is not an error per se.
- The missing else branch linter (which needs to be renamed from `:if`, see #830) now respects the `:level` in the config.
- Added support for `if-not`, `if-some` and `if-let`, for the missing else branch linter, Fixes #791 
- Added tests for `if-some` and adapted ones of `if-let`
> Add missing branch linter for if-* expressions

- doc/editor-integration.md
I've simplified the vscode part of the docs. To me it doesn't make sense to use anything else but the `clj-kondo` extension. Also there was some stuff about Windows there that I don't think is relevant any more.
> Edit the vscode docs

- doc/config.md
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/main_test.clj
Fix for #847 
This linter will warn with **any** usage of `:refer` or `:refer-all` in `:require` clause.
We already have a `:refer-all` linter, which is similar but dedicated to refer-alls (I didn't touch it).
> Add :refer linter, default off

- README.md
Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/clj-kondo ❤️
What it does:
- adds a badge to show the latest number of financial contributors
- adds a banner displaying contributors to the project on GitHub
- adds a banner displaying all individuals contributing financially on Open Collective
- adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website
P.S: As with any pull request, feel free to comment or suggest changes.
Thank you for your great contribution to the Open Source community. You are awesome! 🙌
And welcome to the Open …
> Add Open Collective

- src/clj_kondo/core.clj
- src/clj_kondo/impl/core.clj
- src/clj_kondo/main.clj
- test/clj_kondo/main_test.clj
Solves #862 and #824 
values of multiple --lint and --config options will be conjoined and merged
options that are not supposed to have multiple values such as cache-dir will be
overriden with the right-most value
Examples:
* `--lint foo.clj bar.clj --lint src` -> `["foo.clj" "bar.clj" "src"]`
* `--config edn-str-1 --config edn-str-2` -> `(merge edn-1 edn2)`
* `--cache false --cache` -> `true`
* `--cache-dir some/dir --cache-dir another/dir` -> `another/dir`
> Support multiple options in cli arguments

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/missing_clause_in_try_test.clj
Request adds linting for cases when try is used without any clause `catch` or `finally`.
Linting diff:
```
(missing-clause-in-try ✓) clj-kondo script/diff
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 7214 (delta 23), reused 43 (delta 11), pack-reused 7145
Receiving objects: 100% (7214/7214), 8.03 MiB | 1.28 MiB/s, done.
Resolving deltas: 100% (4153/4153), done.
198d197
< cljs/closure.clj:1969:3: warning: Missing catch or finally in try
1941c1940
< linting took 10927ms, errors: 395, warnings: 1545
---
> linting took 10207ms, errors: 395, …
```
> [#773] Add linting for missing clause in try

- corpus/redundant_do.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/main_test.clj
- test/clj_kondo/missing_body_in_when_test.clj
Request adds linting for `when` expressions with empty body.
```
(missing-body-in-when ✓) clj-kondo script/diff
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 7231 (delta 29), reused 52 (delta 13), pack-reused 7145
Receiving objects: 100% (7231/7231), 8.06 MiB | 2.24 MiB/s, done.
Resolving deltas: 100% (4159/4159), done.
1941c1941
< linting took 10302ms, errors: 395, warnings: 1545
---
> linting took 10896ms, errors: 395, warnings: 1545
```
> [#558] Add linting for missing body in when

- deps.edn
- project.clj
See #889 
The new datalog-parser version fixes or-join semantics.
Before:
```
clojure -A:clj-kondo --lint - <<< "
(ns group
(:require [datomic.api :as d]))
(defn can-access-group? [db user-id group-id]
(boolean
(d/q '[:find ?user-id .
:in $ ?user-id ?group-id
:where [?user :user/id ?user-id]
(or-join [?user ?group-id]
(and [?user :user/group ?g]
[?g :group/id ?group-id])
[?user :user/admin true])]
db user-id group-id)))
"
<stdin>:7:9: error: Join variable not declared inside clauses: [?group-id]
linting took 102ms, errors: 1, warnings: 0
```
After:
```
clojure -A:clj-kondo --lint - <<< "
(ns group
(:require [datomic.api :as d]))
(defn can-access-group? [db user-id group-id]
(boolean
(d/q '[:find ?user-id .
:in $ ?user-id ?group-id
:where [?user :user/id ?user-id]
(or-join [?user …
```
> Bump up datalog-parser to 0.1.3

- analysis/README.md
Hi @borkdude. Thanks for your help on Slack last week. As discussed, here's a PR to update the analysis docs.
Would you expect this much to change? It looks like the keys have changed order and the column positions have incremented by one. What's the chance you changed the column base index from 0 to 1?
**Steps to Generate Example Code**
Follow the docs:
* Create `/tmp/foo.clj`
* Run `clj-kondo` using `clj --main cli-kondo.main` from the repo:
```shell
clj --main clj-kondo.main --lint /tmp/foo.clj --config '{:output {:analysis true :format :edn}}' \
| jet --pretty --query ':analysis'
```
> Document `:from-var`

- doc/build.md
Makes a note that currently only JDK 8 based graal VMs are supported.
Since many clojure devs aren't yet familiar with compiling native
images it's nice to help them stay on a safe path that works.
> docs: note that JDK 8 / 11 based graal is required

- doc/companies.md
- script/install-clj-kondo
Hi borkdude.
Thanks for the wonderful linter. We use it at work :) I'd like to propose a --release-version flag to the install script in order to pin the version. The use case for this is that we want to rely on a pinned version to avoid any accidental bugs in the latest version. In particular, we got bit by https://github.com/borkdude/clj-kondo/issues/944 which led to some CI churn.
Example usage: `script/install-clj-kondo --dir $PWD/foo --release-version 2020.06.12`
Thoughts? Happy to change the option name to whatever you prefer.
Cheers, Gabriel
> Provide option to pin install to a specific version

- src/clj_kondo/main.clj
When copy pasting the url from the terminal (e.g. by double-clicking + ctr-c/cmd-c) the dot gets included and you end up at a [non-existing page](https://cljdoc.org/d/clj-kondo/clj-kondo/2020.06.21/doc/configuration.) instead of [target page](https://cljdoc.org/d/clj-kondo/clj-kondo/2020.06.21/doc/configuration).
This commit removes that dot to fix this situation. Here is [some background](https://www.punctuationmatters.com/should-i-use-punctuation-after-a-url/) on this issue. Apparently other tools can deal with this, my terminal not yet
> Remove trailing dot from url in help message

- doc/config.md
`:list-as` -> `:lint-as` in doc
> Minor typo

- doc/config.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/unused_bindings_test.clj
By @dharrigan:
It is sometimes useful to include the `:as` when destructuring maps because it
can help to identify similarily named functions, but with different inputs,
and thus acts as a form of documentation.
For example:
`(defn foo [{:keys [bar] :as config}] bar)`
Whilst `config` is not used, it is at least documented and easy to spot when
scanning through the code.
This commit, which solves #1016, introduces a new exclude-binding option
called `exclude-destructured-as` which, when set to true, will tell the linter to
ignore any unused :as bindings.
> [#1016] option to exclude :as from unused bindings

- doc/install.md
Adding install instructions for using the repositories and the AppImage.
FYI, it also generates a Docker image. I don't use Docker, but it gave the following info along with it:
```
This container can be pulled via:
docker pull registry.opensuse.org/home/zilti/clojure/containers/clj-kondo:latest
Set DOCKER_CONTENT_TRUST=1 to enable image tag verification.
```
> Adding install instructions for using the repositories and the AppImage.

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/format_test.clj
Fixes #1042.
Output of `script/diff`:
```
-R is deprecated, use -A with repl, -M for main, or -X for exec
WARNING: When invoking clojure.main, use -M
remote: Enumerating objects: 239, done.
remote: Counting objects: 100% (239/239), done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 9109 (delta 109), reused 150 (delta 59), pack-reused 8870
Receiving objects: 100% (9109/9109), 10.93 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (5220/5220), done.
WARNING: Use of :main-opts with -A is deprecated. Use -M instead.
WARNING: When invoking clojure.main, use -M
1c1
< "Elapsed time: 11.48637 msecs"
---
> "Elapsed time: 10.536513 …
```
> [#1042] fix format false positive on relative indexing

- src/clj_kondo/impl/linters.clj
- test/clj_kondo/core_test.clj
Extends the findings for :unused-referred-vars to include the namespace and name of the unused variable.
The impetus for this is reporting and removing unused-refers in [carve](https://github.com/borkdude/carve) - hopefully a PR for that will be along after this.
This was not testable via `lint!`, which parses the linter output for metadata. (name and namespace are not included in that output)
> Include namespace and name in unused-refer findings

- .circleci/config.yml
- .circleci/script/release
I was unable to native-image the previously generated standalone.jar with graalvm8-20.2 or with graalvm11-20.2.
I've not changed the circleci run steps to use script/compile because I didn't want to change too much around.
Both +clj-1.10.2 and +native-image have to be enabled for it to work, otherwise there are different errors.
(I could provide logs if this is of interest.)
> circleci: remove jvm job step "create uberjar" and store compiled -standalone.jar per platform as artifact

- analysis/README.md
- src/clj_kondo/core.clj
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/analysis_test.clj
As described in #982, this is to add an extra level of analysis to kondo for other tools.
A new config output flag `:locals` to turn this on.
`:scope-end-col` and `:scope-end-row` are important keys on the `:locals` analysis for completion type tools that need to know at what positions a var is valid for (using the `:end-row` and `:end-col` of a symbol is sufficient for start of completion in most cases but an argument could be made for a more explicit `:scope-start-row/col`.
The `:str` is important to know how an expr appears in code as it is difficult (impossible?) to recreate the string from the symbol and namespace with namespaced keywords and destructuring differences.
Locally I have 5 failing tests on master, and this branch has the same, so it seems like an environment problem that …
> Fixes #982 Adds locals to analysis with an extra config flag

- parser/clj_kondo/impl/rewrite_clj/node/protocols.clj
- src/clj_kondo/impl/linters/keys.clj
- test/clj_kondo/impl/analyzer_test.clj
- test/clj_kondo/main_test.clj
Implements https://github.com/clj-kondo/clj-kondo/issues/1056.
Output of `script/diff`: 
```
remote: Enumerating objects: 9672, done.
remote: Total 9672 (delta 0), reused 0 (delta 0), pack-reused 9672
Receiving objects: 100% (9672/9672), 11.04 MiB | 5.55 MiB/s, done.
Resolving deltas: 100% (5594/5594), done.
1c1
< "Elapsed time: 8.203851 msecs"
---
> "Elapsed time: 8.956134 msecs"
1966c1966
< clojure/tools/reader.clj:18:53: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? reader-conditional second' tagged-literal whitespace?]
---
> clojure/tools/reader.clj:18:53: warning: use alias or :refer [char desugar-meta …
```
> [#1056] Detect duplicate key in '{[1 2] 3, (1 2) 4}

- src/clj_kondo/impl/linters.clj
- test/clj_kondo/main_test.clj
Fix for [1116](https://github.com/clj-kondo/clj-kondo/issues/1116).
It would be cool to get the `lint!` fn from clj-kondo-test-utils to test against both clj and cljs (or at least have an option to allow it) but I couldn't figure that out. This fixes the issue, but I'd appreciate input on how we could prevent regression (espeically when adding new specific-call linters) by use of tests.
> Add cljs.core cases in `lint-specific-calls!`

- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/analysis_test.clj
Added to namespace-definitions.
Added to defprotocol, catch.
namespace-usages name-* points to the last piece of a namespace.
namespace-usages alias-* points to the position of the alias token.
Adds to https://github.com/clj-kondo/clj-kondo/pull/1110 a couple positions were missed and after working at integrating into clojure-lsp, the need for positioning in the namespace-definitions and the namespace-usages is also needed.
> Add name-* positions to more things.

- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/analysis_test.clj
src/clj_kondo/impl/analyzer/namespace.clj:431:15: warning: unused binding meta-name
test/clj_kondo/analysis_test.clj:99:46: warning: unused binding locals
test/clj_kondo/analysis_test.clj:99:54: warning: unused binding local-usages
linting took 1115ms, errors: 0, warnings: 3
> Fixing lints

- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/single_operand_test.clj
Unsure whether to combine this with :single-operand-comparison or not. Happy to merge the two if that's a better approach.
> [#1099] Add :single-operand-logical linter for `and` and `or`

- CHANGELOG.md
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/main_test.clj
Fixes https://github.com/clj-kondo/clj-kondo/issues/1078.
Output of `script/diff`:
```
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 9754 (delta 29), reused 48 (delta 11), pack-reused 9672
Receiving objects: 100% (9754/9754), 11.10 MiB | 5.71 MiB/s, done.
Resolving deltas: 100% (5623/5623), done.
1c1
< "Elapsed time: 10.222993 msecs"
---
> "Elapsed time: 9.500667 msecs"
1966c1966
< clojure/tools/reader.clj:18:53: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? reader-conditional second' tagged-literal …
```
> [#1078] Detect periods contained in lib names inside prefix lists

- src/clj_kondo/impl/analyzer/usages.clj
- test/clj_kondo/analysis_test.clj
Had to use `get-namespace` because `(:ns ctx)` doesn't get updated on `analyze-require` (and probably the other namespace-altering fns).
> Fixes #1153 

- corpus/schema/defmethod.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/schema.clj
Closes: https://github.com/clj-kondo/clj-kondo/issues/1174
--
I preferred to go with the approach to track the `fn-sym` and `index` instead of trying to infer when the vector was supposed to be the arguments or the dispatch value (for any schema.core macro) because the inferring logic was going to be more complex (in the code or even computationally) and would probably still have some bugs in corner cases when using the `:-` keyword inside function bodies
> Fix schema.core/defmethod linting for vectors dispatch-values

- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/analysis_test.clj
Add missing `name-row`, `name-col`, `name-end-row` and `name-end-col` fields to analyzed var-usages on require form
> [analysis] Fix missing position fields on require form analysis

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/main_test.clj
Fix for #1184
@borkdude is it just this simple?
> Mark let as top-level, so redefined-vars inside are caught

- doc/config.md
Original unresolved-symbol link in config.md went to a non-existent hash, updated it to the intended doc
> Update unresolved-symbol link in config.md

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/hooks_test.clj
Addressing #1198.
`source/diff` output
```
-R is deprecated, use -A with repl, -M for main, or -X for exec
WARNING: Use of :main-opts with -A is deprecated. Use -M instead.
WARNING: When invoking clojure.main, use -M
remote: Enumerating objects: 248, done.
remote: Counting objects: 100% (248/248), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 10943 (delta 108), reused 165 (delta 59), pack-reused 10695
Receiving objects: 100% (10943/10943), 11.51 MiB | 2.96 MiB/s, done.
Resolving deltas: 100% (6318/6318), done.
WARNING: Use of :main-opts with -A is deprecated. Use -M instead.
WARNING: When invoking clojure.main, use …
```
> Expose config key to hook fn

- analysis/README.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/usages.clj
- test/clj_kondo/analysis_test.clj
This PR should fix a issue we have on clojure-lsp. When we hover over a local or local-usage we highlight the references:
But when a local is a function, it shows incorrectly the range:
This also affect features like rename.
This happens because clj-kondo send only the row and column of the local-usage and not the name-* like we do for var-usages and other buckets.
Another example of the issue [here](https://clojurians.slack.com/archives/CPABC1H61/p1615928222016500?thread_ts=1615910590.010200&cid=CPABC1H61)
> [analysis] Add name positions to local-usage analysis

- CHANGELOG.md
- README.md
- doc/config.md
- src/clj_kondo/core.clj
- src/clj_kondo/impl/core.clj
- src/clj_kondo/main.clj
- test/clj_kondo/impl/copy_config_test.clj
This will allow clj-kondo to copy hooks while returning findings/analysis, used by clojure-lsp for example.
This can be considered a breaking-change, not sure we should keep checking for no-warnings along with the new flag.
> Change no-warnings to copy-hooks check when copying hooks

- analysis/README.md
- corpus/hooks/state_flow.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/common.clj
- src/clj_kondo/impl/analyzer/test.clj
- test/clj_kondo/analysis_test.clj
Fixes #1216 
This should add the `:defined-by` with the full-qualified-symbol for all `var-definitions`.
> [analysis] Add defined-by on missing var definitions

- src/clj_kondo/impl/utils.clj
- test/clj_kondo/analysis_test.clj
Docstrings returned via :doc in analysis are no longer over-escaped.
Fix is to simply call `sexpr` on string node.
Lemme know if this works for you.
Fixes #1223
> Correct escaping for docstrings in analysis

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/main_test.clj
Both these functions wrap their bodies in a 0-arity thunk (see #1081)
> Fix recur arities for lazy-seq and lazy-cat

- parser/clj_kondo/impl/rewrite_clj/parser/token.clj
- test/clj_kondo/impl/analyzer_test.clj
- test/clj_kondo/impl/parser_test.clj
- test/clj_kondo/main_test.clj
This allows editor plugins to place the squiggly lines below the entire token instead of right at the end.
> Report reader errors at the start of token

- analysis/README.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer/usages.clj
- test/clj_kondo/analysis_test.clj
Fix #1156
- Add `auto-resolved` field to keyword analysis
- Add `namespace-from-prefix` field to keyword analysis
- Fix ns overide for namespace maps like `#:a{:b/c 1}` the correct `:ns` should be `:b`  not `:a`
> Improve keywords analysis

- corpus/shadow_cljs/dot_alias.cljs
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/unused_namespace_test.clj
Normalization was working incorrectly for namespace aliases containing
dots in it because they were mistaken for property access in cljs.
Now symbol normalization checks if the symbol is an alias before
assuming it a property access.
Closes #1248.
> Add ns alias check to symbol normalization

- corpus/spec_syntax.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/spec.clj
- test/clj_kondo/main_test.clj
Lint maps keys within `clojure.spec.alpha/keys` forms to warn if keys other than `:req`, `:opt`, `:req-un`, and `:opt-un` are used.
Output of `/script/diff` on my machine:
```diff
1904c1904
< clojure/tools/reader.clj:18:53: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? reader-conditional second' tagged-literal whitespace?]
---
> clojure/tools/reader.clj:18:53: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? second' whitespace?]
2169c2169
< inlined/clj_kondo/impl/toolsreader/v1v2v2/clojure/tools/reader.clj:16:87: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? …
```
> Lint clojure.spec.alpha/keys

- src/clj_kondo/impl/core.clj
- test/clj_kondo/impl/inactive_config_test.clj
Now only reporting detected imported clj-kondo configs from libraries
if they are not already specified in :config-paths in clj-kondo config.
Closes #1256
> Refine messaging around importing configs

- doc/linters.md
- src/clj_kondo/impl/analyzer/namespace.clj
This PR adds a new configuration option to the `:use` linter to permit excluding certain nses from the lint.
As it stands, on my machine there are two tests that fail, but they fail on my machine even without my changes, so this PR adds no failing tests.
The implementation I have here is very simplistic, just a one-liner, and I'd like some input on if this matches about what you'd like.
Before I mark this PR ready for merge I'll want to finish all the following tasks.
> Add :exclude config for the :use linter

- doc/jvm.md
This change will not shutdown the watch worker.
Relates to https://github.com/thheller/shadow-cljs/issues/910
> Update example for shadow-cljs

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/datalog.clj
- src/clj_kondo/impl/analyzer/jdbc.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/analyzer/spec.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/core.clj
- src/clj_kondo/impl/findings.clj
- src/clj_kondo/impl/linters.clj
- src/clj_kondo/impl/linters/deps_edn.clj
- src/clj_kondo/impl/linters/keys.clj
- src/clj_kondo/impl/namespace.clj
- src/clj_kondo/impl/utils.clj
- Allow pass a `:level` to `reg-finding!`.
- Remove unused `:level` from `reg-finding!` calls
> Allow override finding level

- .clj-kondo/config.edn
- src/clj_kondo/impl/hooks.clj
- test/clj_kondo/impl/hooks_test.clj
- test/clj_kondo/test_utils.clj
Allow hooks to obtain ns analysis, when cached.
This is useful, for example, to rewrite macros that make implicit use of some symbols from other namespaces.
The implementation provides `hooks-api/ns-analysis`, which takes a  namespace symbol and returns any cached analysis for that namespace.  The returned map is keyed by language keyword (`:cl` and `:cljs`) and each value is a map keyed by a defined symbol.  The value for each  symbol is a subset of the information provided in the [analysis var-definitions](https://github.com/clj-kondo/clj-kondo/blob/master/analysis/README.md#data)
The function can also take an option map, with `:lang` specifying the source file language (`:clj`, `:cljs`, or `:cljc`)for which analysis should be returned. The default is to return analysis for all …
> Expose ns-analysis fn in hooks api

- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
We recognize that deps.edn and bb.edn differ slightly in what elem types
they support for :paths.
- deps.edn - strings or keywords
- bb.edn - strings onlys
When reporting on data type errors, I've favoured generic English words
over specific class names. For example instead of:
Expected vector, found: clojure.lang.PersistentHashMap
We report:
Expected vector, found: map
Closes #1353
> Lint bb.edn and deps.edn :paths for data type

- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
Apply current deps.edn :deps linting to bb.edn.
Also, instead of:
Expected map, found: java.lang.String
We now report:
Expect map, found: string
Closes #1357
> Lint bb.edn :deps

- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/analysis_test.clj
This should help differ var-usages that are inside a :refer from a var-usage elsewhere in the code:
```clojure
(ns a
(:require
[clojjure.string :refer [split-lines]]))
split-lines
```
the first `split-lines` should has a `:refer true` while the other one should not.
> [analysis] Add :refer to var-usages when inside a require

- src/clj_kondo/impl/findings.clj
This fixes https://github.com/clojure-lsp/clojure-lsp/issues/554
During the call of `:custom-lint-fn` when clojure-lsp is starting, clojure-lsp async reg-finding! to not block the project initialization, this can cause outdated findings later on that will only be fixed if user manually go to the file or edit the file.
With this PR the `:custom-lint-fn` return the finding if it was really applied/not ignored by any ignore or some configuration, then clojure-lsp can ignore the finding if not applied.
I didn't find any issues on changing the `reg-finding!` to not always return `nil` but let me know if you see any problems with that.
> Make reg-finding! return the finding if it was applied/not ignored

- CHANGELOG.md
- analysis/README.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/analysis_test.clj
- test/clj_kondo/core_test.clj
- Add `:end-row` and `:end-col` for all var-usages when using as a function call
- rollback https://github.com/clj-kondo/clj-kondo/commit/4f74945fb050210e82f76d9a9e5293a633a23b22 as we already have `:name-*` for var-usage name location
Related to https://github.com/clojure-lsp/clojure-lsp/issues/569
> [analysis] Add scope-end-row and scope-end-col to var-usages

- doc/config.md
I have tried to make it very explicit, very clear that clj-kondo/config is just an example of a repo with exports and is not required - some users might misinterpret the previous text, I think.
> Importing: clarify clj-kondo/config is an ex.

- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/docstring.clj
- test/clj_kondo/docstring_format_test.clj
This PR is in response to #805 
It adds basic formatting checks on docstrings; leading and trailing whitespace, blank docstrings and summaries (first line of docstring should be a complete sentence).
Some notes on the implementation
- These only lint existing docstrings; use the existing `:missing-docstring` linter to check that docstrings exist at all.
- The naming of the linters is taken from the [clojure styleguide](https://guide.clojure.style/#documentation).
- All linters except "blank docstring" are off by default - there is a blank docstring in `clojure/core_deftype.clj` which triggers the `script/diff` check.
- This patch also modifies the analyser to find docstrings in `defprotocol` and set `:doc` in the resulting vars metadata.
- `:doc` entries in metadata on symbols are linted …
> Add simple docstring formatting linters.

- doc/dev.md
- src/clj_kondo/impl/config.clj
- test/clj_kondo/test_utils.clj
When running the test suite locally, non-default settings in the user's home may cause tests to fail.
The changes address this by:
- explicitly setting default values for linter options that a user may want to adapt
- using the default config as a base for the tests to merge into
> Avoid local test failure caused by personal clj-kondo settings

- CHANGELOG.md
- doc/editor-integration.md
This pull request corresponds to #827. With Clojure support for Sublime Text (e.g. tonsky's [Clojure Sublimed](https://github.com/tonsky/Clojure-Sublimed)), it would be useful to add instructions on how to get support for using clj-kondo in the editor.
> Add Sublime Text instructions

- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
This was caused by an insufficient test case. The task maps only contained one element each, so the `last` used on the task definition entries always chose a entry for `:depends`. Fixed by extending the conditions in `doseq` to do a proper match.
> match on :depends instead of defaulting to last element.

- doc/ci-integration.md
The commit referenced in the example points to an old version of setup-clj-kondo.
Since https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
the old version of the Action no longer runs, but the updated version does run.
> Update setup-clj-kondo example

- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
don't lint presence of doc strings in private tasks since they currently have no function in babashka.
> ignore missing doc string on private tasks

- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
only consider entries where:
- key is a symbol
- task def is a map
> fix cycle detection in bb.edn. fixes #1584

- doc/linters.md
`:unsorted-required-namespace` -> `:unsorted-required-namespaces`
> Fix typo in linters.md

- CHANGELOG.md
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/impl/config_test.clj
Based on a [slack conversation](https://clojurians.slack.com/archives/CHY97NXE2/p1647025453421829)
Allows a workflow when one needs to replace linters, but keep default paths for custom hooks to be found.
> Support nested ^:replace overrides in config

- doc/install.md
As per https://github.com/clj-kondo/clj-kondo/issues/1622, I found that I didn't need to use `arch -x86_64` to `brew install`. Leaving both possibilities present in the docs.
- [ n/a ] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions
- [ n/a ] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.
> Update instructions for running on M1 Macs [1622]

- .github/pull_request_template.md
- script/setup-musl
zlib is used during Linux static builds using musl.
Upstream released a new version and removed the old one (1.2.11). This PR bumps it to the latest version, and also add `--fail` flag to `curl` to make it easier to debug another similar error in the future.
> Bump zlib to version 1.2.12

- test/clj_kondo/re_frame_test.clj
add https://github.com/athensresearch/athens cljs code snapshot as is
now to lint against
> [#1638] Test to catch lint regressions caused by re-frame analysis

- src/clj_kondo/impl/config.clj
Move :simple-libspec inside the :unused-namespace map
- [_] This PR correponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
- [_] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions
- [_] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.
> Fix typo in default-config

- src/clj_kondo/core.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/core.clj
- test/clj_kondo/core_test.clj
- test/clj_kondo/impl/analyzer_test.clj
This adds `:files-done` to the `file-analyzed-fn`, this is useful because usually clients want to know how many files we already analyzed, not only the total.
@bokdude I know we already have the `files` atom, but on parallel it's not reliable for this feature as it will swap all files before starts analyzing it, it'd result in a wrong number when we trigger the file-analyzed-fn call.
> Add :files-done to file-analyzed-fn

- doc/linters.md
Issue #1680 was resolved by digging through already supported options and figuring out that the unused namespaces linter supports the `:simple-libspec` option. This PR updates the documentation to include it.
~- [ ] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions~ Not applicable
~- [ ] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.~ Not applicable
> Updates docs for unused-namespace option

- doc/hooks.md
Two categories of changes:
1. Additions of lil bits and bobs throughout from my recent experience adding hooks to `lilactown.helix`
2. Moving the `## Clojure code as rewrite-clj nodes` somewhere earlier. I'm not sure if where I did eventually relocate it is best, but I do know that I felt a strong feeling of "dang this section is not where I expect to be" as I went back and forth referring to this doc when making the hooks.
> Update hooks.md with more info + maybe relocate a section

- doc/config.md
The `:namespace-name-mismatch` linter has been re-enabled by default but the documentation was not reflecting it. Follow up of [74ab2f5019b9743a2343a5771e033a669524c5ce].
> Fix optional linters documentation

- CHANGELOG.md
- src/clj_kondo/impl/types.clj
- test/clj_kondo/types_test.clj
Fixes #1735
The simplest solution that I could figure out right away. The only obvious weakness would be performance, there may be a way to run the nil checking code less often?
> Add `nilable` as an option to map type specs.

- CHANGELOG.md
- src/clj_kondo/impl/analysis.clj
- test/clj_kondo/analysis_test.clj
When a var is defined by potemkin/import-vars, we know which namespace it was imported from. This patch exposes that info in the analysis. This will permit a fix for https://github.com/clojure-lsp/clojure-lsp/issues/1020
> Expose imported-ns in analysis

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/invalid_arity_test.clj
Gives mapcat the same special handling as map for situations where it's being used as a transducer inside sequence and thus can have its internal function called with arities above 1.
Fixes #1755.
> #1755: Fix mapcat transducer invalid-arity false positives

- CHANGELOG.md
- analysis/README.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/analysis_test.clj
This adds the dispatch value to the analysis of defmethods.
Fixes #1716.
> Include dispatch-val in analysis of defmethod

- doc/hooks.md
I found myself struggling trying to write a kondo hook and was trying to figure out how to debug.
It would be lovely to have in the docs an easy snippet to start a REPL with clj-kondo loaded in it, rather than starting `clj` assuming it's already on the class path.
> Add -Sdeps to REPL example in hooks tips

- CHANGELOG.md
- deps.edn
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/core_test.clj
(cc'ing @ericdallo)
Hi,
could you please consider a patch to simplify the logic around what to pass as the filename URI to the `file-analyzed-fn` as discussed in #1782 starting with https://github.com/clj-kondo/clj-kondo/issues/1782#issuecomment-1228920239
The analyzer, without this patch, will pass a nil URI to the `file-analyzed-fn` when there is a request for a nested jar file. As discussed, It is better instead to pass in the already calculated input `uri` argument rather than construct on the fly from the `filename` which might leave the URI as nil.
As also discussed in the above thread, and  is now obvious from the additional test vector, the analyzer will return "unconventional" URIs for the nested jar files, such as `"jar:file:file:/.*/corpus/withcljdir.jar!/dirinjar.clj/arity.clj" …
> Pass existing filename URI to file-analyzed-fn

- CHANGELOG.md
- corpus/config_in_ns/my_custom_ns.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/config_in_ns_test.clj
> Add support for filename-pattern on ns-group

- CHANGELOG.md
- doc/linters.md
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/main_test.clj
- test/clj_kondo/unknown_require_option_test.clj
Warns on unknown `:require` option pairs. Includes no options as I can't think of any reason to include that at this time.
Closes #1460
> Add :unknown-require-option

- CHANGELOG.md
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/main_test.clj
---
Found when working on other stuff.
Closes #1810
> Ignore incorrect class symbols error objects when analyzing imports

- CHANGELOG.md
- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/bindings_test.clj
Fixes #1821
---
Relatively simple change:
1. Check if the vector has an `:as` binding and if the `:exclude-destructured-as` is set.
2. If so, store the vector's last child as `as-sym`.
3. When looping over the vector's children, if the expr matches the `as-sym`, mark binding as used on context (same as how map destructuring works).
Closes #1821
> Include vectors in :exclude-destructured-as

- CHANGELOG.md
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/discouraged_var_test.clj
Fixes an issue where merged configs (config-in-comment, config-in-ns, ns-metadata, etc.) that updated the :level in `discouraged-var` to :off were ignored.
> fix: discouraged-var :level :off w/ merged configs

- doc/install.md
As of 2022.06.22 we now have a MacOS aarch64 (M1-compatible) binary via #1728.
> Remove Rosetta2 from installation docs

- .pre-commit-hooks.yaml
- see discussion in #1864 
just sets the docker pre-commit hook to the last stable tagged release. This will get bumped next time a release is cut
> reset docker hook to stable image tag

- .clj-kondo/config.edn
- deps.edn
- project.clj
- test/clj_kondo/analysis/java_test.clj
- test/clj_kondo/test_utils.clj
Of note:
- experiment currently limited to clj-kondo.analysis.java-test ns
- updated .clj-kondo/config.edn to ignore matcher-combinators' match? assert expr
Closes #1869
> unit tests: explore using matcher-combinators lib

- CHANGELOG.md
- src/clj_kondo/impl/core.clj
- test/clj_kondo/single_operand_test.clj
> Don't warn about single arg use when there's a second arg in a reader conditional

- doc/ci-integration.md
To not show the `clj-kondo` usage info when there's no staged `.clj[cs]?$' files.
> Add `--no-run-if-empty` arg to pre-commit hook

- doc/ci-integration.md
From the manual
```
-r      Compatibility with GNU xargs.  The GNU version of xargs runs the utility argument at least once, even if xargs input is empty, and it supports a -r
option to inhibit this behavior.  The FreeBSD version of xargs does not run the utility argument on empty input, but it supports the -r option for
command-line compatibility with GNU xargs, but the -r option does nothing in the FreeBSD version of xargs.
```
> Use backwards-compatible option for xargs

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/unresolved_symbol_test.clj
Fixes #1984
During development I noticed clj-kondo already not mark as unresolved java.lang classes, so AFAICS we don't need to change anything, I added a test to test java.lang is linted correctly.
> Lint constructor calls providing unresolved-symbol

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/invalid_arity_test.clj
Adds support for arity detection with `send`, `send-off`, `send-via`, `swap-vals!`, and `update-in!`.
> More hof invalid arity detection

- doc/linters.md
The default level of `:dynamic-var-not-earmuffed` was changed from `:warning` to `:off` by #1970.
- I think this PR is likely a sufficient statement of the problem and proposed solution.
> Update linters.md: `:dynamic-var-not-earmuffed` is `:off` by default

- doc/linters.md
The default level of `:namespace-name-mismatch` was changed from `:off` to `:error` by commit 74ab2f5019b9743a2343.
See also commit 16cd3f88bd5a14ec40c1.
- I think this PR is likely a sufficient statement of the problem and proposed solution.
> Update linters.md: `:namespace-name-mismatch` is `:error` by default

- CHANGELOG.md
Mismatches between link text and link URL found with:
```
cat CHANGELOG.md | \
grep -o '\[#[0-9]\+\](https://github.com/clj-kondo/clj-kondo/\(issues\|pull\)/[0-9]\+)' | \
perl -n -e 'print unless /^\[#([0-9]+)\].*\/\1\)$/;'
```
> Fix GitHub Issue/PR links in CHANGELOG.md

- doc/cljdoc.edn
- src/aaaa_this_has_to_be_first/because_patches.clj
- src/aaaa_this_has_to_be_first/pprint.clj
- src/clj_kondo/hooks_api.clj
- src/clj_kondo/impl/analysis/java.clj
- src/clj_kondo/impl/analyzer/clojure_data_xml.clj
- src/clj_kondo/impl/analyzer/match.clj
- src/clj_kondo/impl/docstring.clj
- src/clj_kondo/impl/linters/config.clj
- src/clj_kondo/impl/linters/deps_edn.clj
- src/clj_kondo/impl/linters/edn_utils.clj
1) Add omitted articles to `cljdoc.edn`.
2) Suppress internal namespaces by adding `:no-doc` metadata. Current clj-kondo code specifies ns metadata in the `attr-map`, so went with the flow. Ex, used this syntax:
```Clojure
(ns my-ns {:no-doc true})
```
Instead of this syntax:
```Clojure
(ns ^:no-doc my-ns)
```
Closes #2021
> cljdoc: review/update presented API and articles

- doc/linters.md
The "Default level" was left out of linters.md when `:redundant-call` was introduced by #1692.
- I think this PR is likely a sufficient statement of the problem and proposed solution.
> Update linters.md: `:redundant-call` is `:off` by default

- CHANGELOG.md
- corpus/spec_syntax.clj
- src/clj_kondo/impl/analyzer/spec.clj
- test/clj_kondo/main_test.clj
While linting a Clojure project I stumbled upon a syntax error on the [`clojure.spec.alpha/keys`](https://github.com/clojure/spec.alpha/blob/70f26984ee171f816eee6b162b563d403a49bfe8/src/main/clojure/clojure/spec/alpha.clj#L414) regarding the map key `:gen`.
You can find more context on [this #clj-kondo thread](https://clojurians.slack.com/archives/CHY97NXE2/p1680180661821299).
> Add :gen support on clojure.spec.alpha/keys

- doc/docker.md
---
I noticed this error while reading this example to run it myself. Given it's just a typo in the docs and not a functional change, I've skipped all of the above checks.
> Fix `lint stdin` example command

- CHANGELOG.md
- corpus/java/sources/foo/bar/AwesomeClass.java
- deps.edn
- project.clj
- resources/META-INF/native-image/clj-kondo/clj-kondo/native-image.properties
- src/clj_kondo/impl/analysis/java.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/analysis/java_test.clj
> analysis: parse java files via javaparser to produce java-member-definitions

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/analysis_test.clj
- test/clj_kondo/main_test.clj
Metadata applied to protocol name and protocol methods are now included
in analysis data.
Unused private defprotocols and unused private defprotocol methods now
lint to :unused-local-var
Closes #2097
> analyze and act on defprotocol metadata

- CHANGELOG.md
- analysis/README.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/analysis_test.clj
Highlights:
- `:arglists` metadata only overrides `:arglist-strs` if it looks valid
- `:fixed-arities` and `:varargs-min-arity` are never affected by `:arglists` metadata, they always describe original arg lists params, if present
Also includes:
- minor analysis doc update & corrections
Closes #2096
> analysis: :arglists meta applies to :arglist-strs

- CHANGELOG.md
- src/clj_kondo/impl/cache.clj
See https://github.com/cognitect/transit-clj/issues/43
> Use no-flush-outputstream rather than byte array outputstream

- CHANGELOG.md
- doc/linters.md
Adds documentation for `:single-logical-operand` linter to linter docs https://github.com/clj-kondo/clj-kondo/blob/6bca0676674ae784ba487dea150b63567e2b6b2a/src/clj_kondo/impl/linters.clj#L194
Fixes https://github.com/clj-kondo/clj-kondo/issues/2184
Documentation change, no tests
> Add missing documentation for :single-logical-operand linter

- CHANGELOG.md
- doc/config.md
- src/clj_kondo/impl/core.clj
- test/clj_kondo/main_test.clj
Document 'type' template variable, too, while we're at it.
fixes #2192
> Add end-row and end-col template variables

- CHANGELOG.md
- corpus/no_unused_namespace.clj
- doc/linters.md
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/main_test.clj
This adds a linter `:underscore-in-namespace` which warns on the presence of the `_` character in `ns` declarations, as requested in issue #1753.
This also modifies the `corpus/no_unused_namespace.clj` test sample file so that the namespace is named `no-unused-namespace`  instead of `no_unused-namespace`.
> Implemented no underscore linter - #1753

- src/clj_kondo/impl/analyzer.clj
Clj-kondo's datalog linting is really nice. But currently it doesn't work with [datalevin](https://github.com/juji-io/datalevin).
There is currently an easy enough work around which is:
```
{:lint-as {datalevin.core/q datascript.core/q}}  
```
However, seeing as datalevin seems to be popular having support by default would be nice for new users. This change adds datalevin.core/q to the datalog syntax check list.
Appologies for not opening an issue first, I figured this was such a small change that a PR would be easier.
Let me know if I need to make any changes/additions.
> add datalevin.core/q to datalog syntax checking

- CHANGELOG.md
- corpus/invalid_characters.clj
- corpus/invalid_literals.clj
- corpus/invalid_unicode.clj
- parser/clj_kondo/impl/rewrite_clj/parser/token.clj
- test/clj_kondo/main_test.clj
Fixes #2322
As mentioned in https://github.com/clj-kondo/clj-kondo/issues/2322#issuecomment-2132237967 I added an additional clause to check for `:eof` reader-exception types, which surfaces the correct line numbers for invalid literals such as `##`.
The last commit removes those checks altogether (which I felt was unnecessary and brittle) and refactors the logic for better readability. (ie. subjective, can be left out)
Invalid-radix number literals, also mentioned in the original issue, seem to have a deeper root cause in the inlined tools.reader code which might be better reported upstream.
> Report locations for more reader errors

- CHANGELOG.md
- doc/ci-integration.md
- src/clj_kondo/core.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/main.clj
- test/clj_kondo/core_test.clj
- test/clj_kondo/main_test.clj
This is useful for CI where you may not want to display info-level notices if you only require folks to fix warnings or above.
The default level is `info`.
With `--report-level error` will also omit the `, warnings: N` part of the output summary.
If the report level is not recognised, prints the help.
Fixes #2410
> Add new `--report-level` CLI option

- src/clj_kondo/impl/analyzer/usages.clj
I'd like to start chipping away at #2282, as it seems to be stuck in PR limbo 😄. Instead of trying to get the functionality - plus the numerous bits of supporting functionality - merged, I thought it might be best to just make a couple of uncontroversial PRs for the supporting functionality, like this.
I haven't added tests, as none of the other syms except for defn are tested anyway, but for illustrative sake:
Before:
```clojure
(lint! "(fn* [] 1 2)" conf/default-config)
;; => ()
```
After:
```clojure
(lint! "(fn* [] 1 2)" conf/default-config)
;; => ({:file "<stdin>", :row 1, :col 9, :level :warning, :message "Unused value: 1"})
```
> Include fn* in the core-syms that analyze-usages2 checks

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/condition_always_true_test.clj
I just linked this to the original issue (#2272) as I think this should have been implemented there.
This might also be an appropriate time to upgrade this linter from :off to :warning, as the docs say "will be `:warning` in a future release"?
> Include if-not in :condition-always-true linter

- parser/clj_kondo/impl/rewrite_clj/parser/core.clj
- parser/clj_kondo/impl/rewrite_clj/reader.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/impl/parser_test.clj
- test/clj_kondo/main_test.clj
Closes https://github.com/clj-kondo/clj-kondo/issues/2439
Situation:
Reader conditionals are consumed by the Clojure reader. If there's a matching branch, it's returned. If there's no matching branch, the reader moves on. Discard reader macros consume the next form. So when the discard macro attempts to get the next form and there's a reader conditional with no matching branch, the form after the reader conditional is returned.
(+ 1 #_#?(:clj 2) :three 4)
Read as (+ 1 #_ 2 :three 4). The :clj branch of the #? form is used so the next form is 2, #_ ignores it, the result is (+ 1 :three 4).
(+ 1 #_#?(:foo 2) :three 4)
Read as (+ 1 #_ :three 4). The :clj branch of the #? form doesn't exist so the next form is :three, #_ ignores it, the result is (+ 1 4).
(+ 1 #_#?(:clj 2 :default 100) :three …
> Fix #2439: uneval applies to next form which may depend on reader features

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/condition_always_true_test.clj
Include if-let, when-let, if-some, when-some, when-first
Adds to functionality of #2272
Sorry, not meaning to make separate PRs, just hadn't thought of these until just now.
> Include if-let etc in :condition-always-true linter

- src/clj_kondo/impl/analyzer/usages.clj
- test/clj_kondo/unresolved_namespace_test.clj
This fix cases where `:name` was nil on some findings, afetting clojure-lsp analysis for unresolved-namespaces.
> Fix unresolved-namespace :name data

- CHANGELOG.md
- README.md
- src/clj_kondo/impl/analyzer.clj
Clj-kondo users should not be committing the `inline-configs` lock file.
Move it from `./.clj-kondo/.lock` to `./.clj-kondo/.cache/.config-lock` where `./.clj-kondo` will be affected by `--config-dir` but `.cache` will not be affected by `--cache` nor `--cache-dir`.
This keeps the lock file in a constant spot relative to `inline-configs` dir, but now also a directory that clj-kondo users have been advised to git ignore.
Also: add advice on version control to docs.
Closes #2606
> Make inline-configs lock file vcs friendly
