clj-kondo/clj-kondo

- deps.edn
- src/clj_kondo/main.clj
Also only load cache for relevant language
> Performance: transit + prevent unnecessary cache load/write

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/linters.clj
- src/clj_kondo/impl/linters/keys.clj
- src/clj_kondo/impl/macroexpand.clj
- src/clj_kondo/impl/metadata.clj
- src/clj_kondo/impl/namespace.clj
- src/clj_kondo/impl/state.clj
- src/clj_kondo/impl/utils.clj
- src/clj_kondo/main.clj
- test/clj_kondo/impl/analyzer_test.clj
- test/clj_kondo/impl/macroexpand_test.clj
- test/clj_kondo/main_test.clj
> Fix tools.analyzer.jvm false positives

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/linters.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/main_test.clj
optimization: don't traverse entire AST
> refactor inline def

- deps.edn
- doc/config.md
- doc/jvm.md
- project.clj
- src/clj_kondo/core.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/core.clj
- src/clj_kondo/impl/utils.clj
- src/clj_kondo/main.clj
- test/clj_kondo/core_test.clj
- test/clj_kondo/impl/cache_test.clj
- test/clj_kondo/main_test.clj
- test/clj_kondo/profile.clj
- test/clj_kondo/test_utils.clj
> Clojure/JVM API

- appveyor.yml
- Use https://www.appveyor.com/
- Provide auto generated artifcats
> Add CI build for Windows

- corpus/defprotocol.clj
- parser/clj_kondo/impl/rewrite_clj/parser/core.clj
- parser/clj_kondo/impl/rewrite_clj/reader.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/metadata.clj
- src/clj_kondo/impl/parser.clj
- test/clj_kondo/impl/analyzer_test.clj
- test/clj_kondo/main_test.clj
TODO:
```
(defn foo [x y z] ^{:a x :b y :c z} [1 2 3])
```
> [#314] rewrite parsing of metadata

- .circleci/script/docker
- Dockerfile
- Fixes leiningen install
- Removes tools.deps from Docker builds
- Addresses https://github.com/borkdude/clj-kondo/issues/410
> Fix docker build issue

- doc/install.md
The package I wrote for nixos got merged, now it is part of the official packages :)
I just added some notes to the docs.
Closes #414
> docs: mention NixOS package

- doc/editor-integration.md
Add the standard way of installation
> Add instructions for spacemacs develop branch

- src/clj_kondo/impl/types/clojure/core.clj
- add a bunch of specs for simple functions
- add comments for all functions that are still missing specs
---
Any comments are welcome. I thought it a good idea to add comments for everything so you don't have to guess what functions are missing, and editing becomes a tiny bit easier.
I plan to write more specs/types, but don't expect all of them from me. :)
> More types for clojure.core

- src/clj_kondo/impl/types/clojure/core.clj
Here's more types for clojure.core.
I'm not sure if the haskell-style names for the type variables are a good idea. I'm willing to rewrite this commit if someone comes up with better names.
Also ideas for testing the correctness of these type definitions are welcome. I guess running clj-kondo against large known-good codebases would be one idea.
> Types for arithmetic operations

- .circleci/config.yml
This feature is not available to free plans.
> Disable docker layer caching

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/impl/analyzer_test.clj
This small refactor will make it easier to make changes to the analyzer
in future.
> Extract Excetpion->finding code from analyze-input

- corpus/types/insufficient.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/types_test.clj
> [#547] skip arg type check if arity check is disabled

- src/clj_kondo/impl/types/clojure/core.clj
- test/clj_kondo/types_test.clj
Hi. There seems to be a problem with `hash-set` function.
> Add failing hash-set test

- src/clj_kondo/impl/linters.clj
- test/clj_kondo/analysis_test.clj
This is a draft for addressing #568.
> Use improved row and col info for reg-usage!

- deps.edn
- project.clj
- reflection.json
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/impl/analyzer_test.clj
- test/clj_kondo/main_test.clj
Support Datomic datalog syntax (and static semantics) check for datomic, datascript and datahike.
https://github.com/borkdude/clj-kondo/issues/563
> Add datomic datalog syntax checker.

- corpus/deftest.cljc
- src/clj_kondo/impl/config.clj
- test/clj_kondo/test_test.clj
fixes https://github.com/borkdude/clj-kondo/issues/626
> Ignore thrown? in clojure.test/are

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/main_test.clj
> [#655] Support clojure.core/with-local-vars

- src/clj_kondo/impl/types/clojure/core.clj
- test/clj_kondo/types_test.clj
Fixes https://github.com/borkdude/clj-kondo/issues/663
> conj can take nil

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/analysis_test.clj
- test/clj_kondo/main_test.clj
fixes #688
QA'd locally by installing this branch and testing the repro provided in the issue 👍
> Add bound-fn to the analyzer

- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/main_test.clj
As discussed previously, this should take care of #560 and #681.
> Add support for customizing exclusions to :refer :all

- corpus/redundant_do.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/main_test.clj
> Add redundant do check for future

- corpus/redundant_do.clj
- doc/dev.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/main_test.clj
> Add redundant do check for when-let

- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/main_test.clj
> Add linter for conflicting aliases in ns form

- doc/config.md
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/main_test.clj
> Rename :if config key into :missing-else-branch and add doc

- doc/editor-integration.md
Link to article documenting installation and configuration of clj-kondo via LSP.
Resolve #851
> Link to Spacemacs install for clj-kondo via lsp

- src/clj_kondo/main.clj
> Add cljc as a valid option for --lang in usage help

- corpus/redundant_do.clj
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/main_test.clj
> add redundant do check for when-first and when-some

- doc/companies.md
> Sharetribe is using clj-kondo

- README.md
See https://github.com/borkdude/clj-kondo/issues/828
> Add links to podcasts

- doc/config.md
Current docs are good and guided me when writing my first hook.
Hooks aren't scary hard to write, nor are they easy peasy. Here are some changes
to hooks docs that I think might help a bit:
- Let folks know hooks are interpreted with sci
- Introduce the concept of rewrite-clj nodes early so that subsequent references
to nodes have context
- Give the reason why someone might want to write an analyze-call hook earlier
- Try to focus more on the code than its representation as a node
- Give a couple of examples of what Clojure code looks like when parsed into
a rewrite-clj node
- Other minor changes and, hopefully welcome, tweaks.
> Update hooks docs

- doc/editor-integration.md
COC.NVIM diagnostics works amazing, I got it working.
> add coc.nvim, coc-diagnostic setup instructions

- doc/install.md
Heyo. Thanks for merging in the install option quickly. Here's the requested update to the relevant doc
> Mention new install option from #946

- doc/config.md
> Mention nested let* in hook expansion

- README.md
Also provide copy/paste-ready examples for project setup calls for Boot and Clojure CLJ
> Readme: Add --parallel to Project Setup

- doc/editor-integration.md
https://github.com/neomake/neomake/pull/2516#issuecomment-748525033 :tada:
> Add neomake to editor-integration.md

- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/linters.clj
As per #1109 this was pretty straightforward as the information already exists.
> Fixes #1109 adds :name-col :name-row and end to vars

- analysis/README.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/analysis_test.clj
> Add analysis for signature strings

- doc/jvm.md
- tools.deps: qualify clj-kondo
- tools.deps: use -M
> tools deps fixes

- src/clj_kondo/impl/analyzer/usages.clj
- test/clj_kondo/analysis_test.clj
Sorry, I don't know how to link to the issue. The issue I created to describe the problem is #1160.
> Fix for invalid symbols from keyword analysis

- src/clj_kondo/impl/analysis.clj
- test/clj_kondo/analysis_test.clj
> [Analysis] Change keyword analysis :name to string instead of symbol

- doc/hooks.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/hooks_test.clj
> Add tests and update hooks.md

- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/macroexpand.clj
- test/clj_kondo/analysis_test.clj
Fixes for clojure-lsp: https://github.com/clojure-lsp/clojure-lsp/issues/385
> [analysis] Remove generated nodes from local analysis

- doc/linters.md
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/linters.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/unresolved_namespace_test.clj
- test/clj_kondo/unresolved_symbol_test.clj
- test/clj_kondo/unresolved_var_test.clj
> Fixes #1232 introduce report-duplicates linter config

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/impl/analyzer_test.clj
> Add error message when keywords are passed in :or map

- doc/companies.md
We've rebranded! Thanks for continuing to support our developers.
> rename Icebreaker to Gatheround in companies.md

- doc/companies.md
> Add Deon Digital to companies.md

- .circleci/config.yml
- deps.edn
- project.clj
- test/clj_kondo/invalid_arity_test.clj
- test/clj_kondo/main_test.clj
Updates Eastwood, proposes setting it up as a linter, and fixes the related issues in code.
---
Having Eastwood run in more projects would help me in its continued development. Would also go full circle relative to https://github.com/jonase/eastwood/commit/650f1d43c153f313b7f2998e10ab8f81b4fdbed3 !
> Setup Eastwood as a linter

- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
> Update tools-deps linter to match latest CLI release

- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/analysis_test.clj
Fixes #1342
Tested with clojure-lsp as well
> [analysis] Fix `declare` name positions

- src/clj_kondo/impl/analyzer/potemkin.clj
- test/clj_kondo/main_test.clj
> Add support for potemkin full qualified symbols

- src/clj_kondo/impl/findings.clj
- test/clj_kondo/core_test.clj
- Add some docs to the function
- Improve tests to check for reg-finging return
> Improve custom-lint-fn tests

- src/clj_kondo/core.clj
Discussed [here](https://github.com/clojure-lsp/clojure-lsp/issues/331#issuecomment-925785508)
> Expose config functions

- doc/config.md
... now that it has been removed from the config project
> Importing: rm mention of fulcro

- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/main_test.clj
>  Slightly reword :refer suggestion

- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/unused_bindings_test.clj
> Implement :exclude-defmulti-args option

- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/test.clj
- src/clj_kondo/impl/hooks.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/test_test.clj
> [#1492] Add testing-str to analysis context via built-in hook

- .clj-kondo/config.edn
- corpus/.clj-kondo/acme/lib/config.edn
- corpus/acme/lib/example.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/core.clj
- test/clj_kondo/config_paths_test.clj
> Auto config paths

- .dir-locals.el
- .gitignore
- corpus/import_vars.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/potemkin.clj
- test/clj_kondo/analysis_test.clj
- test/clj_kondo/main_test.clj
Fixes https://github.com/clojure-lsp/clojure-lsp/issues/555
I think besides that issue this PR fixes/improve clj-kondo to warn about the not required namespace or consider required namespaces as used and don't complain about unused ones if used inside potemkin macro :)
> Improve potemkin analysis

- doc/install.md
> Add note for how to install on M1 Silicon via Rosetta2

- CHANGELOG.md
- README.md
- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/main_test.clj
> Warn on quoted test constants in case

- CHANGELOG.md
- README.md
- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/main_test.clj
> Warn against 2 argument version of reduce

- CHANGELOG.md
- README.md
- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/main_test.clj
> Repeated arities in multi-arity function

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/potemkin.clj
- test/clj_kondo/analysis_test.clj
> [analysis] Improve potemkin generated var-definitions

- doc/editor-integration.md
> Add clojure extras plugin to docs

- doc/jvm.md
Recommend replace-deps for jvm invocation per https://clojure.org/reference/deps_and_cli#_replace_project_environment_tool
- [-] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions
- [-] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.
> Use :replace-deps for tools

- CHANGELOG.md
- README.md
- doc/linters.md
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
> detect dependance on undefined tasks in bb.edn

- CHANGELOG.md
- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
> Detect and warn on cyclic task dependencies in bb.edn

- doc/linters.md
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters/deps_edn.clj
> do not use qualified keywords for built in linters.

- CHANGELOG.md
- doc/linters.md
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
> implement some more basic linting for bb.edn

- CHANGELOG.md
- analysis/README.md
- src/clj_kondo/core.clj
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/analysis_test.clj
Fixes https://github.com/clj-kondo/clj-kondo/issues/1484
> [analysis] Add protocol impls

- CHANGELOG.md
- corpus/case.clj
- corpus/namespace_name_mismatch/correct_file.clj
- corpus/namespace_name_mismatch/correct_file.cljs
- corpus/namespace_name_mismatch/file-with-dashes.clj
- corpus/namespace_name_mismatch/folder-with-dashes/foo.clj
- corpus/namespace_name_mismatch/ignored.clj
- corpus/namespace_name_mismatch/wrong_file.clj
- corpus/namespace_name_mismatch/wrong_file.cljs
- corpus/namespace_name_mismatch/wrong_file_but_substring.clj
- corpus/namespace_name_mismatch/wrong_folder/foo.clj
- deps.edn
- doc/linters.md
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/namespace_name_mismatch_test.clj
- test/clj_kondo/test_utils.clj
> #1240: Add new linter :namespace-name-mismatch

- doc/install.md
- [yes] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).
- [yes] This PR correponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
- [no] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions
- [no] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.
> Reference maintained AUR helpers

- CHANGELOG.md
- analysis/README.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/analysis_test.clj
Analysis data now includes :protocol-ns and :protocol-name on protocol methods
Closes #1602
> Analysis: add protocol name and ns to its methods

- CHANGELOG.md
- src/clj_kondo/impl/analysis.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/linters.clj
- test/clj_kondo/analysis_test.clj
> [analysis] Add :defmethod true analysis

- CHANGELOG.md
- src/clj_kondo/core.clj
- src/clj_kondo/impl/core.clj
- src/clj_kondo/main.clj
- test/clj_kondo/core_test.clj
> Add option to skip lint

- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/analysis/java_test.clj
> Add name locations to java-class-usages

- CHANGELOG.md
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/analysis_test.clj
To mirror what is available in :var-definitions
> Add :end-row and :end-col to :namespace-definitions

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/analysis_test.clj
> fix #1651: incorrect :protocol-impls implementation

- src/clj_kondo/impl/core.clj
- test/clj_kondo/core_test.clj
> Fix total-files count

- doc/hooks.md
> Doc tools.namespace and tools.build workarounds

- .github/pull_request_template.md
> Typo in pull-request template

- CHANGELOG.md
- doc/config.md
- src/clj_kondo/impl/core.clj
- test/clj_kondo/impl/inactive_config_test.clj
> Update docs and messaging around imported configs

- doc/config.md
- test/clj_kondo/impl/copied_config_test.clj
Addendum for #1697 based on PR discussions.
> Tweaks to docs and tests around imported configs

- .pre-commit-hooks.yaml
- CHANGELOG.md
- doc/ci-integration.md
Add .pre-commit-hook.yaml file to support integration with pre-commit tooling. Check out [pre-commit.com](https://pre-commit.com/) for additional details
> Pre-commit.con hook support

- CHANGELOG.md
- src/clj_kondo/impl/linters/deps_edn.clj
> Don't print to stdout

- CHANGELOG.md
- doc/hooks.md
- src/clj_kondo/hooks_api.clj
- src/clj_kondo/impl/hooks.clj
- test/clj_kondo/hooks_test.clj
Fixing https://github.com/clj-kondo/clj-kondo/issues/1768
> expose `tag` function in `hooks-api`

- CHANGELOG.md
- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
> Add support for sourcehut inferred git dep urls

- CHANGELOG.md
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/main_test.clj
Fix https://github.com/clj-kondo/clj-kondo/issues/1771
> report on empty ns forms instead of crash

- CHANGELOG.md
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/main_test.clj
> Inconsistent scoped alias

- CHANGELOG.md
- corpus/namespace_name_mismatch/correct_file_with_+_sign.clj
- corpus/namespace_name_mismatch/correct_file_with_+_sign.cljs
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/namespace_name_mismatch_test.clj
> Replace munge with namespace-munge when munging namespace

- CHANGELOG.md
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/analysis_test.clj
> Handle location meta more consistently (fix #1812)

- CHANGELOG.md
- src/clj_kondo/impl/analysis/java.clj
> Fix "Too many open files" in java class definition analysis (Closes #1819)

- .circleci/config.yml
- .circleci/script/docker
- .circleci/script/install-clojure
- .circleci/script/install-leiningen
- .circleci/script/release
- .circleci/script/tools.deps
- CHANGELOG.md
- script/compile
> Build linux arm64 in ci

- doc/linters.md
Enhanced the documentation to include a folder mismatch as well and a hint of how to resolve.
There is no issue for this one, just a tiny doc update.
Let me know if I need to create an issue first.
No tests were needed, except checking if the Markdown looked correct.
I have not since it's just a tiny doc update. however if needed, let me know.
> linters.md: "Namespace name mismatch" update

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/analysis_test.clj
- test/clj_kondo/main_test.clj
> Fix #1871 and fix #1879

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/analyzer/usages.clj
- src/clj_kondo/impl/linters.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/unresolved_symbol_test.clj
> Allow forward references in comment forms

- doc/ci-integration.md
> Fix MegaLinter action link in documentation

- CHANGELOG.md
- doc/linters.md
- src/clj_kondo/impl/analyzer/namespace.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/main_test.clj
> Fix #1742: :aliased-namespace-var-usage

- .clj-kondo/config.edn
- CHANGELOG.md
- doc/linters.md
- script/diff
- src/aaaa_this_has_to_be_first/pprint.clj
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/main_test.clj
Hi and sorry for the delay!
As discussed in https://github.com/clj-kondo/clj-kondo/issues/1920 I've added a new linter for this case. I've added tests for the common cases, and some cases that you've listed in the comments/
> Fix #1920: :def-fn linter (@andreyorst)

- CHANGELOG.md
- src/clj_kondo/hooks_api.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/impl/hooks_test.clj
https://github.com/clj-kondo/clj-kondo/issues/1998
> add set-node? and set-node

- .circleci/config.yml
- .circleci/script/docker
- CHANGELOG.md
> Push to GHCR

- CHANGELOG.md
NOTE: The same typo also appears in the #1860 pull request title (and the corresponding git commit message). I'm sure it's not worth rewriting git commit history, but if the #1860 title can be edited, that might be worthwhile.
> fix typo: dymamic => dynamic

- CHANGELOG.md
- doc/linters.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/config.clj
- test/clj_kondo/discouraged_tag_test.clj
Follow up to #2030.
Add a new `:discouraged-tag` linter.
===
> Add a lint for discouraged tag literals.

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/main_test.clj
- I mentioned this issue at https://github.com/clj-kondo/clj-kondo/issues/1920#issuecomment-1474551676 but haven't opened a separate GH issue for it
> False positive `:def-fn` on `def` + `reify`

- README.md
> README: Add shadow-cljs to build-tool specific list

- src/clj_kondo/impl/analysis.clj
- test/clj_kondo/analysis_test.clj
This fixes a breaking change introduced on https://github.com/clj-kondo/clj-kondo/commit/deb8326a24d610b9756989d83d6abb8efde70fa3, clojure-lsp relies on those analysis to provide multiple features
> Rollback removal of clj-kondo/unknown-namespace analysis

- doc/build.md
match current GraalVM version used on CI
> dev docs: update GraalVM version

- CHANGELOG.md
- corpus/clojure_dart/awesome.cljd
- src/clj_kondo/impl/core.clj
- test/clj_kondo/main_test.clj
> Consider cljd files as source files

- corpus/java/sources/foo/bar/AwesomeClass.java
- resources/META-INF/native-image/clj-kondo/clj-kondo/reflect-config.json
- test/clj_kondo/analysis/java_test.clj
This PR fixes the missing reflection issue that happens only with array instantiations.
I could not make a try-catch work for other possible errors because reflection exceptions in the native image are not catch by normal try-catches for some reason, but I tested with a huge java codebase and I believe it's pretty stable now.
> Fix java analysis reflection issues

- src/clj_kondo/impl/analysis/java.clj
This avoids exceptions in the future that may happen during javaparser call
> Add try catch to java analysis

- CHANGELOG.md
- src/clj_kondo/impl/hooks.clj
https://github.com/clj-kondo/clj-kondo/issues/2125
> Fix #2125: clj-kondo.hooks-api/*reload* doesn't work as expected

- corpus/java/sources/foo/bar/AwesomeClass.java
- resources/META-INF/native-image/clj-kondo/clj-kondo/reflect-config.json
- test/clj_kondo/analysis/java_test.clj
Fixes https://github.com/clojure-lsp/clojure-lsp/issues/1624
> Fix javaparser analysis of multi catch blocks for graal

- corpus/java/sources/foo/bar/AwesomeClass.java
- src/clj_kondo/impl/analysis/java.clj
- test/clj_kondo/analysis/java_test.clj
Fixes one more java analysis issue found [here](https://clojurians.slack.com/archives/C01GE5PD249/p1689020049693529?thread_ts=1688654566.524449&cid=C01GE5PD249)
> [java] Fix nested classes javaparser analysis

- CHANGELOG.md
- src/clj_kondo/impl/types/clojure/core.clj
> Changed type of zero? from any->boolean to number->boolean

- CHANGELOG.md
- corpus/issue-2215/.clj-kondo/config.edn
- corpus/issue-2215/.clj-kondo/hooks/clojure/test.clj
- corpus/issue-2215/fail.clj
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/hooks_test.clj
> Fix #2215: passthrough hook should not affect linting

- doc/linters.md
> Fix typos in linters.md

- doc/install.md
> Add ASDF installation notes

- src/clj_kondo/impl/analysis/java.clj
Fixes a warning introduced in #2262. Fixes #2279.
> Eliminate warning from shadowing clojure.core/update-vals

- CHANGELOG.md
- doc/linters.md
> Add :java-static-field-call to doc/linters.md

- src/clj_kondo/impl/linters/deps_edn.clj
- test/clj_kondo/deps_edn_test.clj
> Fix typo, determistic -> deterministic

- doc/config.md
> Remove stray backtick

- doc/config.md
> Document :filename-pattern

- CHANGELOG.md
- src/clj_kondo/impl/sarif.clj
- test/clj_kondo/output_test.clj
Issue #2345
- Fix the nesting level of `region` under the `results` property
- Enhance SARIF output
- Add Clj-kondo `version` to the SARIF output
- Add `endLine` and `endColumn` to the linting results
- Add `helpUri`, `level` and `enabled` to the linting rules
- Remove `artifacts` key as it did not contain any additonal data
from what is available under the results key.
(This is based on the suggestion of the SARIF [validator](https://sarifweb.azurewebsites.net/Validation))
-----
```clojure
(ns bad-clojure
(:require
[clojure.test :refer :all]
[clojure.string :as str]))
(defn- foo [bar] nil)
```    
<details>
<summary> SARIF output</summary>
```json
{
"version": "2.1.0",
"$schema": "https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-schema-2.1.0.json",
"runs": [
{ …
```
> Fix #2345: SARIF output fix and some enhancements

- CHANGELOG.md
- doc/linters.md
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/namespace.clj
- test/clj_kondo/main_test.clj
> Fix #2394 add option to enable require sorting with case sensitivity

- CHANGELOG.md
- src/clj_kondo/impl/analyzer/namespace.clj
- test/clj_kondo/impl/analyzer_test.clj
> Detect empty 'require' and ':require' forms

- CHANGELOG.md
- src/clj_kondo/impl/macroexpand.clj
- test/clj_kondo/bindings_test.clj
- test/clj_kondo/invalid_arity_test.clj
- test/clj_kondo/redundant_call_test.clj
> Check for even number of clauses for cond-> and cond->>

- doc/linters.md
> docs: minor: update linters.md: new default levels

- doc/linters.md
> Fix :keyword-binding linter example

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- test/clj_kondo/format_test.clj
Just adding printf to vars linted by analyze-format
> Add printf to vars linted by analyze-format

- CHANGELOG.md
- doc/hooks.md
- doc/linters.md
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/macroexpand.clj
- test/clj_kondo/do_template_test.clj
> Fix #2475: add :do-template linter

- CHANGELOG.md
- src/clj_kondo/impl/linters/config.clj
- test/clj_kondo/clj_kondo_config_test.clj
- test/clj_kondo/do_template_test.clj
> Fix #2463: false positive when min-clj-kondo-version is specified

- CHANGELOG.md
- src/clj_kondo/core.clj
- src/clj_kondo/impl/config.clj
- src/clj_kondo/impl/linters/config.clj
- test/clj_kondo/clj_kondo_config_test.clj
- test/clj_kondo/do_template_test.clj
Note: this PR is based on commits from #2480 as without the fixes there the tests I added failed on the false positives fixed in that PR.
> Fix #2464: set min-clj-kondo-version finding location when applicable

- src/clj_kondo/hooks_api.clj
- src/clj_kondo/impl/hooks.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/impl/hooks_test.clj
Resolves #2483
@borkdude let me know if this works for you
> Add `quote-node` and `quote-node?` to hooks API

- CHANGELOG.md
- src/clj_kondo/impl/analyzer.clj
- src/clj_kondo/impl/utils.clj
- test/clj_kondo/main_test.clj
> Fix empty alias call

- CHANGELOG.md
- analysis/README.md
See https://clojurians.slack.com/archives/CHY97NXE2/p1742570802468329 for details and discussion
> Document special cases of var-usages location info

- doc/linters.md
> docs: linters: fix typo in code example

- script/compile
- script/compile.bat
> dev: fix stale compile scripts
